In [132]:
import numpy as np
import pandas as pd

In [133]:
data = pd.read_csv("/Users/matthewdunn/Dropbox/CosmicAnalysis/Raw_Data.csv")

In [134]:
name = data.MutationCDS
newlist = list(name.values)
myre = '((\d{4})(?=\D{1})|(\d{3})(?=\D{1})|(\d{2})(?=\D{1}))'
finallist = []
for x in newlist:
    y = re.search(myre,x)
    if y != None:
        finallist.append(y.group(1))
    else:
        finallist.append("")
data['NT'] = finallist
data.NT = data.NT.replace('',np.nan)

In [141]:
data = data.dropna(axis=0, how='any')
data.Count = data.Count.astype(int, inplace=True)
data.sort_values('NT', axis=0, inplace=True)
data.NT = data.NT.astype(int, inplace=True)
data.set_index(data.NT, inplace=True)
data.head()

,Gene,PositionAA,MutationCDS,MutationAA,MutationIDCOSM,Count,MutationType,NT,mean
NT,,,,,,,,,
45,TERT,45,c.1-45G>T,p.?,COSM1717369,4,Unknown,45,4.000000
54,TERT,54,c.1-54C>A,p.?,COSM1717370,1,Unknown,54,4.333333
57,TERT,57,c.1-57A>C,p.?,COSM1717366,11,Unknown,57,6.000000
58,TERT,58,c.1-58C>T,p.?,COSM1717383,1,Unknown,58,1.000000
67,TERT,67,c.1-67C>T,p.?,COSM1717386,1,Unknown,67,1.000000

In [149]:
tp53values = data.loc[data.Gene == 'TP53']
def f(x):
    ser = tp53values.Count[(tp53values.NT >= x) & (tp53values.NT < x+100)]
    return ser.mean()
tp53values['mean'] = tp53values.NT.apply(f)
tertvalues

/Users/matthewdunn/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,Gene,PositionAA,MutationCDS,MutationAA,MutationIDCOSM,Count,MutationType,NT,mean
NT,,,,,,,,,
45,TERT,45,c.1-45G>T,p.?,COSM1717369,4,Unknown,45,61.894737
54,TERT,54,c.1-54C>A,p.?,COSM1717370,1,Unknown,54,66.380952
57,TERT,57,c.1-57A>C,p.?,COSM1717366,11,Unknown,57,63.500000
58,TERT,58,c.1-58C>T,p.?,COSM1717383,1,Unknown,58,66.000000
67,TERT,67,c.1-67C>T,p.?,COSM1717386,1,Unknown,67,60.347826
69,TERT,69,c.1-69G>A,p.?,COSM1717387,1,Unknown,69,63.045455
72,TERT,72,c.1-72C>G,p.?,COSM1717371,1,Unknown,72,66.000000
77,TERT,77,c.1-77C>T,p.?,COSM1717372,1,Unknown,77,60.347826
101,TERT,101,c.1-101C>T,p.?,COSM1717382,1,Unknown,101,51.740741
124,TERT,124,c.1-124C>T,p.?,COSM1716558,1115,Unknown,124,43.843750
124,TERT,124,c.1-124C>A,p.?,COSM1716563,21,Unknown,124,43.843750
129,TERT,129,c.1-129delG,p.?,COSM1717381,1,Unknown,129,8.900000
138,TERT,138,c.1-138C>T,p.?,COSM1717364,2,Unknown,138,9.172414
139,TERT,139,c.1-139_1-138CC>TT,p.?,COSM1716560,8,Unknown,139,9.428571
141,TERT,141,c.1-141G>T,p.?,COSM1717373,1,Unknown,141,9.481481
146,TERT,146,c.1-146C>T,p.?,COSM1716559,219,Unknown,146,10.458333
630,TERT,210,c.630C>T,p.A210A,COSM1310500,1,Substitution - coding silent,630,2.254237
1936,TERT,646,c.1936C>T,p.R646C,COSM4005837,1,Substitution - Missense,1936,1.000000
2576,TERT,859,c.2576G>A,p.R859Q,COSM3776145,1,Substitution - Missense,2576,1.000000

In [ ]:
tertvalues = data.loc[data.Gene == 'TERT']
def f(x):
    ser = tertvalues.Count[(tertvalues.NT >= x) & (tertvalues.NT < x+100)]
    return ser.mean()
tertvalues['mean'] = tertvalues.NT.apply(f)

In [137]:
def rollBy(what, basis, window, func):
    def applyToWindow(val):
        chunk = what[(val<=basis) & (basis<val+window)]
        return func(chunk)
    return basis.apply(applyToWindow)

In [155]:
np.searchsorted([1,2,3,4,5,8,120], 2)

1

In [110]:
rollingwindow = pd.rolling_window(data.Count, window=10, win_type='boxcar')

In [111]:
print rollingwindow

NT
45        NaN
54        NaN
57        NaN
58        NaN
67        NaN
69        NaN
72        NaN
77        NaN
91        NaN
101       2.4
113       2.1
124     113.5
124     114.5
129     114.5
137     114.5
138     114.6
139     115.3
141     115.3
141     115.3
145     115.4
146     137.2
153      25.8
154      24.0
156      24.0
162      24.0
166      23.9
166      23.2
173      23.2
175      23.1
176      23.0
        ...
950       1.6
955       1.5
957       1.5
958       1.5
960       1.3
960       1.4
973       1.4
973       1.4
974       1.3
974       1.1
976       1.1
987       1.1
991       1.5
993       1.5
994       1.6
1006      1.5
1020      1.5
1024      1.6
1031      1.6
1036      1.6
1049      1.6
1050      1.6
1057      1.2
1066      1.2
1101      1.1
1123      1.2
1129      1.2
1147      1.1
1936      1.1
2576      1.1
Name: Count, dtype: float64